services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - upd8-network
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: upd8
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - upd8-network

networks:
  upd8-network:

volumes:
  dbdata:
